### ISSUE TITLE
Volatility Calculator App Error

### ISSUE THREAD

**Issue by jokmalee** [FinancialMarkets/5MinuteFinance#212]
<img width="1016" alt="Screen Shot 2022-07-29 at 2 23 42 PM" src="https://user-images.githubusercontent.com/93644636/181749540-00bcafcb-6a1e-4864-81a7-52530cf1e2e7.png">

The Interactive App to calculate Volatility from a Stock ticker and date range seems to be throwing an error
https://www.5minutefinance.org/concepts/black-scholes

No matter what I put I get:

An error has occurred. Check your logs or contact the app author for clarification.

**Comment by Matt-Brigida** [comment]
Thanks for opening the issue.  The error is because the app uses an out-of-date version of the `quantmod` package.  The app will run using an up-to-date version.  The [code for the app is here](https://github.com/FinancialMarkets/5MinuteFinance/blob/master/Options/black_scholes/single_apps/app2/app2.Rmd) in case you want to run it locally.  

I also [pushed an working version of the app here](https://brigida.shinyapps.io/app2/).  Unfortunately I don't have access to push the app to the URL the [5minutefinance](https://www.5minutefinance.org/) page links to, so it will stay broken there for a while.
